---
- name: Download docker images
  hosts: all
  tasks:
    - name: Pull images
      docker_image:
        name: "{{item}}"
        source: pull
      with_items:
        - nginx
        - tomcat
        - wordpress
        - mysql
        - ghost
