---
- name: Create user on all the servers
  hosts: all
  serial: 1
  tasks:
    - name: User creation
      user:
        name: Ravi
        password: intelliqit
        uid: 1234
        home: /tmp/Ravi
        shell: /bin/bash
        comment: "a regular user"


...
