---
- name: Install git on all servers based on OS flavour
  hosts: all
  tasks:
    - name: Install git on Ubuntu servers uisng apt
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install git in Redhat servers using yum
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
